version: '3'
services:
  santa:
    build: .
    volumes:
      - .:/app
      - ${HOST_GOOGLE_KEYFILE}:${GOOGLE_KEYFILE}
      - ${HOME}/.aws/credentials:/root/.aws/credentials
    environment:
      - AWS_DEFAULT_REGION
      - S3_BUCKET
      - IAM_GROUP
      - GOOGLE_KEYFILE
      - GOOGLE_SPREADSHEET_ID
    entrypoint:
      - python
      - santa.py
